Update build-original-config.yml

diff --git a/.github/workflows/build-original-config.yml b/.github/workflows/build-original-config.yml
--- a/.github/workflows/build-original-config.yml
+++ b/.github/workflows/build-original-config.yml
@@ -27,16 +27,17 @@ on:
 env:
   REPO_URL: https://github.com/openwrt/openwrt
   REPO_BRANCH: master
-  FEEDS_CONF: openwrt.feeds.conf.default
-  CONFIG_FILE: .config
-  DIY_P1_SH: diy-part01new.sh
-  DIY_P2_SH: diy-part02new.sh
+  #FEEDS_CONF: openwrt.feeds.conf.default
+  CONFIG_FILE: config/.config202503120003
+  DIY_P1_SH: ARMv8/diy-part01.sh
+  DIY_P2_SH: ARMv8/diy-part02.sh
   UPLOAD_BIN_DIR: false
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: true
   TZ: Asia/Shanghai
-  FILE_NAME: ARMv8_origin
-  PRODUCT_NAME: ARMv8_orogin
+  FILE_NAME: OpenWrt-NVA
+  PRODUCT_NAME: OpenWrt-NVA
+  OPENWRT_TAG: OpenWrt-NVA
   
 jobs:
   build:
@@ -68,27 +69,15 @@ jobs:
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
-        
-        sudo -E apt-get -qq update
-        sudo -E apt-get -qq full-upgrade -y
-        
-        #sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc 
-        sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
-        sudo systemctl stop mysql
-        sudo apt-get purge mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*
-        sudo rm -rf /etc/mysql /var/lib/mysql /var/log/mysql
-        sudo apt-get remove --purge mysql-\* 
-        sudo apt-get autoremove
-        sudo apt-get autoclean
-        sudo apt-get install mysql-server mysql-client
-        sudo systemctl daemon-reload
-        
-        sudo -E apt-get -qq update
-        sudo -E apt-get -qq full-upgrade -y
-        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/very20101/Openwrt_retry/main/ubutun2204-update)
-        sudo -E apt-get -qq autoremove --purge
-        sudo -E apt-get -qq clean
+        docker rmi $(docker images -q)
+        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
+        sudo swapoff -a && sudo rm -f /swapfile /mnt/swapfile
+        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
+        (sudo -E apt-get -y update
+        sudo -E apt-get -y install clang rename $(curl -fsSL is.gd/depends_ubuntu_2204)
+        sudo -E systemctl daemon-reload
+        sudo -E apt-get -y autoremove --purge
+        sudo -E apt-get -y clean 
         sudo timedatectl set-timezone "$TZ"
         sudo mkdir -p /workdir
         sudo chown ${USER}:${GROUPS} /workdir
@@ -102,9 +91,11 @@ jobs:
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
         cd openwrt
         useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>date: %cd<br/>commit: %s<br/>commit hash: %H")
+        echo "VERSION_INFO=$VERSION_INFO" >> $GITHUB_ENV
+        echo "VERSION_INFO=$(echo $VERSION_INFO)" >> $GITHUB_OUTPUT
         echo "useVersionInfo=$useVersionInfo" >> $GITHUB_ENV
         echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
-        echo "DATE1=$(date "+%y-%m-%d")" >> $GITHUB_ENV
+        echo "DATE1=$(date "+%Y-%m-%d")" >> $GITHUB_ENV
         
     #- name: toolchain cache
      # uses: klever1988/cachewrtbuild@main
@@ -149,34 +140,36 @@ jobs:
         make download -j8
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
+        df -Th
         
     - name: Compile the firmware
       id: compile
       run: |
         cd openwrt
-        rm -rf feeds/packages/net/bind/Makefile
-        wget -O feeds/packages/net/bind/Makefile https://raw.githubusercontent.com/very20101/Openwrt_retry/main/Makefile-bind
-        rm -rf package/small-package/brook/patches/010-chore-deps-update-iploc-to-fix-build-with-mips.patch
+        make defconfig
+        git clone -b main https://github.com/very20101/openwrt_retry packages/op-retry
+        #rm -rf feeds/packages/lang/ruby
+        #cp -rf packages/op-retry/pkg_modified/ruby feeds/packages/lang/ruby
         echo -e "$(nproc) thread compile"
         make -j$(nproc) || make -j1 || make -j1 V=s
         echo "status=success" >> ${GITHUB_OUTPUT}
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+        echo "build_tag=OpenWrt_Armvirt_$(date +"%m.%d.%H%M")" >> ${GITHUB_OUTPUT}
         echo "build_tag=ARMv8_origin_$(date +"%m.%d.%H%M")" >> ${GITHUB_OUTPUT}
         
     - name: Upload OpenWrt Firmware to Release
       uses: ncipollo/release-action@main
-      if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
+      #if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
       with:
-        tag: ${{ steps.compile.outputs.build_tag }}
+        name: OpenWrt-NVA
+        tag: ${{ env.OPENWRT_TAG }}
+        makeLatest: true
+        replacesArtifacts: true
         artifacts: openwrt/bin/targets/*/*/*rootfs.tar.gz
         allowUpdates: true
         token: ${{ secrets.GITHUB_TOKEN }}
-        
-    - name: Check space usage
-      if: (!cancelled())
-      run: df -hT
       
     - name: Clean up server space
       if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
