Update packaging_Novak-ophub.yml

diff --git a/.github/workflows/packaging_Novak-ophub.yml b/.github/workflows/packaging_Novak-ophub.yml
--- a/.github/workflows/packaging_Novak-ophub.yml
+++ b/.github/workflows/packaging_Novak-ophub.yml
@@ -24,10 +24,10 @@ jobs:
       if: (!cancelled())
       run: |
         [ -d openwrt-armvirt ] || mkdir -p openwrt
-        #openwrt_url="$(curl -H "authorization: Bearer ${{ secrets.GH_TOKEN }}" -s "https://api.github.com/repos/very20101/Openwrt_retry/releases/latest | grep -o "*rootfs.tar.gz" )"
+        #openwrt_url="$(curl -H "authorization: Bearer ${{ secrets.GH_TOKEN }}" -s "https://api.github.com/very20101/Openwrt_retry/releases/latest | grep "*rootfs.tar.gz" )"
         #[[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
         wget -q -P openwrt https://github.com/very20101/Openwrt_retry/releases/download/latest/openwrt-armvirt-64-default-rootfs.tar.gz
-        [[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
+        #[[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
         #wget -q -P openwrt https://github.com/very20101/Openwrt_retry/releases/download/OpenWrt_Armvirt_01.27.1503/openwrt-armvirt-64-default-rootfs.tar.gz
         echo "status=success" >> $GITHUB_OUTPUT
         echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
