Update pack_Nova.yml

diff --git a/.github/workflows/pack_Nova.yml b/.github/workflows/pack_Nova.yml
--- a/.github/workflows/pack_Nova.yml
+++ b/.github/workflows/pack_Nova.yml
@@ -52,15 +52,21 @@ jobs:
         echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
         echo "DATE1=$(date +"%y.%m.%d")" >> $GITHUB_ENV
 
-    - name: Download Armvirt Firmware
-      id: download
+    - name: Get OpenWrt firmware
+      id: build
+      if: (!cancelled())
       run: |
-        FIRMWARE_PATH=openwrt/bin/targets/armvirt/64
-        [ -d $FIRMWARE_PATH ] || mkdir -p $FIRMWARE_PATH
-        #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
-        #FIRMWARE_URL=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/download/OpenWrt-NewK" | grep -o "ROOTFS_$VERSION.*rootfs.tar.gz")
-        wget -q -P $FIRMWARE_PATH https://github.com/very20101/Openwrt_retry/releases/download/OpenWrt-Nova/openwrt-armsr-armv8-generic-rootfs.tar.gz 
+        [ -d openwrt-armvirt ] || mkdir -p openwrt
+        cd openwrt
+        curl -s https://api.github.com/repos/very20101/Openwrt_retry/releases/latest | grep "browser_download_url.*tar.gz" | cut -d : -f 2,3 | tr -d \" | wget -qi -
+        #openwrt_url="$(curl -H "authorization: Bearer ${{ secrets.GH_TOKEN }}" -s "https://api.github.com/very20101/Openwrt_retry/releases/latest | grep "*rootfs.tar.gz" )"
+        #[[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
+        #wget -q -P openwrt https://github.com/very20101/Openwrt_retry/releases/download/latest/openwrt-armvirt-64-default-rootfs.tar.gz
+        #[[ "${?}" -ne "0" ]] && echo -e "The armvirt file download failed!" && exit 1
+        #wget -q -P openwrt https://github.com/very20101/Openwrt_retry/releases/download/OpenWrt_Armvirt_01.27.1503/openwrt-armvirt-64-default-rootfs.tar.gz
         echo "status=success" >> $GITHUB_OUTPUT
+        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
+        echo "DATE1=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
 
     - name: Package OpenWrt Firmware
       if: steps.download.outputs.status == 'success'
